services:
  microservicio1:
    container_name: microservicio1_c
    image: faridaquino/microservicio1:v5
    env_file:
      - .env1
    ports:
      - "8084:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/ms1/api/v1/auth/health"]
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 5
    restart: always

  microservicio2:
    container_name: microservicio2_c
    image: faridaquino/microservicio2:v4
    env_file:
      - .env2
    ports:
      - "8083:8005"
    depends_on:
      microservicio1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/ms2/"]
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 5
    restart: always

  microservicio3:
    container_name: microservicio3_c
    image: faridaquino/microservicio3:v1
    env_file:
      - .env3
    ports:
      - "8082:8000"
    depends_on:
      microservicio2:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ms3/"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  microservicio4:
    container_name: microservicio4_c
    image: faridaquino/microservicio4:v4
    env_file:
      - .env4
    ports:
      - "8081:8080"
    depends_on:
      microservicio3:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    
  microservicio5:
    container_name: microservicio5_c
    image: faridaquino/microservicio5:v1
    env_file:
      - .env5
    ports:
      - "8085:8005"
    depends_on:
      microservicio4:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    
  microservicio6:
    container_name: microservicio6_c
    image: faridaquino/microservicio6:v2
    env_file:
      - .env6
    ports:
      - "8086:8000"
    depends_on:
      microservicio5:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

















